description: |
  Performs a login to the OpenShift server, either via username and password,
  certificate authority file, or a token.
  Upon a successful login, the kubectl configuration file (kubeconfig) will
  be updated with the OpenShift cluster access credentials.

parameters:
  server-address:
    description: |
      The address of the OpenShift server (in the form hostname:port).
    type: string
  username:
    description: |
      Used for login via username and password.
      Specifies the username for logging into the OpenShift server.
      (Do not set the "certificate-authority" and "token" parameters if login via username
      and password credentials is desired)
    type: string
    default: ""
  password:
    description: |
      Used for login via username and password.
      Specifies the password for logging into the OpenShift server.
      (Do not set the "certificate-authority" and "token" parameters if login via username
      and password credentials is desired)
    type: string
    default: ""
  certificate-authority:
    description: |
      Used for login via certificate authority.
      Specfiies the path to the certificate authority file for logging into the OpenShift server.
      (Do not set the "username", "password" and "token" parameters if login via certificate
      authority is desired)
    type: string
    default: ""
  token:
    description: |
      Used for login via token.
      Specifies the bearer token for authentication to the API server
    type: string
    default: ""
  insecure-skip-tls-verify:
    description: |
      If true, the server's certificate will not be checked for validity. This will
      make your HTTPS connections insecure.
    type: boolean
    default: false
  project:
    description: |
      Specifies a project to switch to after the login.
      If none is specified, the default project will be used.
    type: string
    default: ""
  openshift-cli-release-tag:
    description: |
      The version of the OpenShift CLI to be installed, if it is
      not already installed. Defaults to the latest stable version.
    type: string
    default: ""
  openshift-platform-version:
    description: |
      The version of the OpenShift platform that the cluster is on.
    type: enum
    enum: ["3.x","4.x"]
steps:
  - install-openshift-cli:
      release-tag: << parameters.openshift-cli-release-tag >>
  - run:
      name: Perform login (and kubeconfig update)
      command: |
        SERVER_ADDRESS="<< parameters.server-address >>"
        USERNAME="<< parameters.username >>"
        PASSWORD="<< parameters.password >>"
        CERTIFICATE_AUTHORITY="<< parameters.certificate-authority >>"
        TOKEN="<< parameters.token >>"
        INSECURE_SKIP_TLS_VERIFY="<< parameters.insecure-skip-tls-verify >>"
        if [ -n "${SERVER_ADDRESS}" ]; then
          set -- "$@" "${SERVER_ADDRESS}"
        fi
        if [ -n "${USERNAME}" ]; then
          set -- "$@" --username="${USERNAME}"
        fi
        if [ -n "${PASSWORD}" ]; then
          set -- "$@" --password="${PASSWORD}"
        fi
        if [ -n "${CERTIFICATE_AUTHORITY}" ]; then
          set -- "$@" --certificate-authority="${CERTIFICATE_AUTHORITY}"
        fi
        if [ -n "${TOKEN}" ]; then
          set -- "$@" --token="${TOKEN}"
        fi
        if [ "${INSECURE_SKIP_TLS_VERIFY}" == "true" ]; then
          set -- "$@" --insecure-skip-tls-verify=true
        fi
        oc login "$@"
  - run:
      name: Switch to project
      command: |
        PROJECT="<< parameters.project >>"
        if [ -n "${PROJECT}" ]; then
          oc project ${PROJECT}
        else
          echo "No project specified; default project will be used."
        fi

